server:
  port: 8762
spring:
  application:
    name: zuul

zuul:
  ignoredServices: '*'
  routes:
    inventory:
      path: /service/inventory/**
      serviceId: inventory
      stripPrefix: true
    files:
      path: /service/files/**
      servcieId: files
      stripPrefix: true
    manager:
      path: /
      serviceId: manager

eureka:
  fetchRegistry: true
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
